import { ReactNode } from 'react';
import QueryProvider from './query-provider';
import { Metadata } from 'next';
import { inter } from '@/shared/lib/theme';
import { Locale, NextIntlClientProvider } from 'next-intl';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const AppProvider = ({ children, locale }: { children: ReactNode; locale: Locale }) => {
  return (
    <html lang={locale}>
      <body className={`${inter.className} flex min-h-screen flex-col antialiased`}>
        <NextIntlClientProvider>
          <QueryProvider>{children}</QueryProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
};

export default AppProvider;
